### ISSUE TITLE
No need to set promicuous mode

### ISSUE THREAD

**Issue by gmag11** [TenoTrash/ESP32_ESPNOW_RSSI#2]
Hi, I discovered this repo 2 or 3 months ago. It great, thanks. I've developed a project that makes intensive use of ESP-NOW with ESP8266 and ESP32. It is called [EnigmaIOT](https://github.com/gmag11/EnigmaIOT), have a look if you like :)

Recently Espressif released a video in youtube showing many uses of ESP-NOW communication:
[![ESP-NOW communication](https://img.youtube.com/vi/QmvMtgNs9r8/0.jpg)](https://www.youtube.com/watch?v=QmvMtgNs9r8)

They have another [GitHub repository](https://github.com/espressif/esp-now) where they show a method similar to yours except it does not use promiscuous mode.

It seems that promiscuous mode is working under the hood of ESP NOW. So when you receive a packet, you already have all metadata some memory positions before payload buffer. Have a loo to [this line](https://github.com/espressif/esp-now/blob/master/components/espnow/src/espnow.c#L132).

I've checked that it works both on ESP8266 and ESP32. The only difference is that doing so RSSI is added 98 dB. So you need to substract 98 to get value in dBm units.

This is how [I've implemented it](https://github.com/gmag11/EnigmaIOT/blob/dev/src/espnow_hal.cpp#L119):

```c++
void ICACHE_FLASH_ATTR Espnow_halClass::rx_cb (uint8_t* mac_addr, uint8_t* data, uint8_t len) {
    espnow_frame_format_t* espnow_data = (espnow_frame_format_t*)(data - sizeof (espnow_frame_format_t));
    wifi_promiscuous_pkt_t* promiscuous_pkt = (wifi_promiscuous_pkt_t*)(data - sizeof (wifi_pkt_rx_ctrl_t) - sizeof (espnow_frame_format_t));
    wifi_pkt_rx_ctrl_t* rx_ctrl = &promiscuous_pkt->rx_ctrl;
    
    if (Espnow_hal.dataRcvd) {
        Espnow_hal.dataRcvd (mac_addr, data, len, rx_ctrl->rssi - 98); // rssi should be in dBm but it has added almost 100 dB. Do not know why
	}
}
```

**Comment by TenoTrash** [comment]
Nice! Will test it and maybe incorporate into the project! Thanks!!!

**Comment by CRprog** [comment]
Hello, is there any news regarding this issue ?
Is it a good idea to do it this way, or does it make things more complicated ? 
Regards.

**Comment by TenoTrash** [comment]
Hello, I was away for a long time with another projects, will return soon here. Feel free to fork this project and make the modifications you mention, and will also update in my blog! Cheers!!!
